/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/tasks/": {
    /** List Tasks */
    get: operations["list_tasks_tasks__get"];
    /** Create Task */
    post: operations["create_task_tasks__post"];
  };
  "/tasks/{task_id}": {
    /** Get Task */
    get: operations["get_task_tasks__task_id__get"];
    /** Delete Task */
    delete: operations["delete_task_tasks__task_id__delete"];
    /** Update Task */
    patch: operations["update_task_tasks__task_id__patch"];
  };
  "/projects/": {
    /** List Projects */
    get: operations["list_projects_projects__get"];
    /** Create Project */
    post: operations["create_project_projects__post"];
  };
  "/projects/{project_id}": {
    /** Get Project */
    get: operations["get_project_projects__project_id__get"];
    /** Delete Project */
    delete: operations["delete_project_projects__project_id__delete"];
    /** Update Project */
    patch: operations["update_project_projects__project_id__patch"];
  };
  "/projects/{project_id}/velocity": {
    /** Get Project Velocity */
    get: operations["get_project_velocity_projects__project_id__velocity_get"];
  };
  "/users/": {
    /** List Users */
    get: operations["list_users_users__get"];
    /** Create User */
    post: operations["create_user_users__post"];
  };
  "/users/{user_id}": {
    /** Get User */
    get: operations["get_user_users__user_id__get"];
    /** Delete User */
    delete: operations["delete_user_users__user_id__delete"];
    /** Update User */
    patch: operations["update_user_users__user_id__patch"];
  };
  "/invoices/": {
    /** List Invoices */
    get: operations["list_invoices_invoices__get"];
    /** Create Invoice */
    post: operations["create_invoice_invoices__post"];
  };
  "/invoices/{invoice_id}": {
    /** Get Invoice */
    get: operations["get_invoice_invoices__invoice_id__get"];
    /** Delete Invoice */
    delete: operations["delete_invoice_invoices__invoice_id__delete"];
    /** Update Invoice */
    patch: operations["update_invoice_invoices__invoice_id__patch"];
  };
  "/invoices/{invoice_id}/approval-steps": {
    /** Get Approval Steps */
    get: operations["get_approval_steps_invoices__invoice_id__approval_steps_get"];
    /** Create Approval Step */
    post: operations["create_approval_step_invoices__invoice_id__approval_steps_post"];
  };
  "/intelligence/search": {
    /** Semantic Search */
    post: operations["semantic_search_intelligence_search_post"];
  };
  "/intelligence/agent-logs": {
    /** Get Agent Logs */
    get: operations["get_agent_logs_intelligence_agent_logs_get"];
  };
  "/intelligence/agents/trigger/{agent_type}": {
    /**
     * Trigger Agent
     * @description Manually trigger an agent by type. Valid types: task_monitor, approval_nudger, timesheet_drafter
     */
    post: operations["trigger_agent_intelligence_agents_trigger__agent_type__post"];
  };
  "/intelligence/parse-pdf": {
    /** Parse Pdf */
    post: operations["parse_pdf_intelligence_parse_pdf_post"];
  };
  "/intelligence/index-document": {
    /** Index Document */
    post: operations["index_document_intelligence_index_document_post"];
  };
  "/": {
    /** Root */
    get: operations["root__get"];
  };
  "/health": {
    /** Health Check */
    get: operations["health_check_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AgentLogResponse */
    AgentLogResponse: {
      /** Id */
      id: string;
      /** Action */
      action: string;
      /** Context */
      context: Record<string, never>;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Status */
      status: string;
    };
    /** ApprovalStepCreate */
    ApprovalStepCreate: {
      /** Stage */
      stage: string;
      /** Assigneeemail */
      assigneeEmail: string;
      /** Requireddocs */
      requiredDocs: string[];
      /**
       * Deadline
       * Format: date-time
       */
      deadline: string;
    };
    /** ApprovalStepResponse */
    ApprovalStepResponse: {
      /** Id */
      id: string;
      /** Invoiceid */
      invoiceId: string;
      /** Stage */
      stage: string;
      /** Requireddocs */
      requiredDocs: string[];
      /** Assigneeemail */
      assigneeEmail: string;
      /** Status */
      status: string;
      /**
       * Deadline
       * Format: date-time
       */
      deadline: string;
      /** Lastnudgedat */
      lastNudgedAt: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InvoiceCreate */
    InvoiceCreate: {
      /** Projectid */
      projectId: string;
      /** Amount */
      amount: number;
      /** Pdfurl */
      pdfUrl?: string | null;
    };
    /** InvoiceResponse */
    InvoiceResponse: {
      /** Id */
      id: string;
      /** Projectid */
      projectId: string;
      /** Amount */
      amount: number;
      /** Status */
      status: string;
      /** Pdfurl */
      pdfUrl: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** InvoiceUpdate */
    InvoiceUpdate: {
      /** Amount */
      amount?: number | null;
      /** Status */
      status?: string | null;
      /** Pdfurl */
      pdfUrl?: string | null;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Healthscore
       * @default 0
       */
      healthScore?: number;
      /**
       * Velocity
       * @default 0
       */
      velocity?: number;
    };
    /** ProjectResponse */
    ProjectResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Healthscore */
      healthScore: number;
      /** Velocity */
      velocity: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** ProjectUpdate */
    ProjectUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Healthscore */
      healthScore?: number | null;
      /** Velocity */
      velocity?: number | null;
    };
    /** SearchRequest */
    SearchRequest: {
      /** Query */
      query: string;
      /**
       * Top K
       * @default 5
       */
      top_k?: number;
      /** Filter Type */
      filter_type?: string | null;
    };
    /** SearchResult */
    SearchResult: {
      /** Score */
      score: number;
      /** Text */
      text: string;
      /** Metadata */
      metadata: Record<string, never>;
    };
    /** TaskCreate */
    TaskCreate: {
      /** Projectid */
      projectId: string;
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /**
       * Status
       * @default BACKLOG
       */
      status?: string;
    };
    /** TaskResponse */
    TaskResponse: {
      /** Id */
      id: string;
      /** Projectid */
      projectId: string;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /** Status */
      status: string;
      /**
       * Lastupdated
       * Format: date-time
       */
      lastUpdated: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** TaskUpdate */
    TaskUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Status */
      status?: string | null;
    };
    /** UserCreate */
    UserCreate: {
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Timesheetstatus
       * @default pending
       */
      timesheetStatus?: string;
      /** Githubusername */
      githubUsername?: string | null;
    };
    /** UserResponse */
    UserResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Email */
      email: string;
      /** Timesheetstatus */
      timesheetStatus: string;
      /** Githubusername */
      githubUsername: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Name */
      name?: string | null;
      /** Email */
      email?: string | null;
      /** Timesheetstatus */
      timesheetStatus?: string | null;
      /** Githubusername */
      githubUsername?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List Tasks */
  list_tasks_tasks__get: {
    parameters: {
      query?: {
        project_id?: string | null;
        status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Task */
  create_task_tasks__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Task */
  get_task_tasks__task_id__get: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Task */
  delete_task_tasks__task_id__delete: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Task */
  update_task_tasks__task_id__patch: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Projects */
  list_projects_projects__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"][];
        };
      };
    };
  };
  /** Create Project */
  create_project_projects__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Project */
  get_project_projects__project_id__get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Project */
  delete_project_projects__project_id__delete: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Project */
  update_project_projects__project_id__patch: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Project Velocity */
  get_project_velocity_projects__project_id__velocity_get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Users */
  list_users_users__get: {
    parameters: {
      query?: {
        timesheet_status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create User */
  create_user_users__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User */
  get_user_users__user_id__get: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete User */
  delete_user_users__user_id__delete: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update User */
  update_user_users__user_id__patch: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Invoices */
  list_invoices_invoices__get: {
    parameters: {
      query?: {
        project_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InvoiceResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Invoice */
  create_invoice_invoices__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvoiceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["InvoiceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Invoice */
  get_invoice_invoices__invoice_id__get: {
    parameters: {
      path: {
        invoice_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InvoiceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Invoice */
  delete_invoice_invoices__invoice_id__delete: {
    parameters: {
      path: {
        invoice_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Invoice */
  update_invoice_invoices__invoice_id__patch: {
    parameters: {
      path: {
        invoice_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvoiceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InvoiceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Approval Steps */
  get_approval_steps_invoices__invoice_id__approval_steps_get: {
    parameters: {
      path: {
        invoice_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApprovalStepResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Approval Step */
  create_approval_step_invoices__invoice_id__approval_steps_post: {
    parameters: {
      path: {
        invoice_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApprovalStepCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ApprovalStepResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Semantic Search */
  semantic_search_intelligence_search_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResult"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Agent Logs */
  get_agent_logs_intelligence_agent_logs_get: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AgentLogResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Trigger Agent
   * @description Manually trigger an agent by type. Valid types: task_monitor, approval_nudger, timesheet_drafter
   */
  trigger_agent_intelligence_agents_trigger__agent_type__post: {
    parameters: {
      path: {
        agent_type: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Parse Pdf */
  parse_pdf_intelligence_parse_pdf_post: {
    parameters: {
      query: {
        pdf_url: string;
        invoice_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Index Document */
  index_document_intelligence_index_document_post: {
    parameters: {
      query: {
        doc_id: string;
        text: string;
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Health Check */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
